// AUTO-GENERATED by scripts/generate_juno_v1_frontend_types.py; do not edit by hand.
// Source: deployment/juno-v1-testnet.template.json

export type JunoV1CodeIdKey = "astroport-factory" | "astroport-incentives" | "astroport-native-coin-registry" | "astroport-oracle" | "astroport-pair" | "astroport-router" | "astroport-tokenfactory-tracker" | "astroport-whitelist" | "cw20-base";

export type JunoV1AddressKey = "astroport-factory" | "astroport-incentives" | "astroport-native-coin-registry" | "astroport-oracle" | "astroport-router" | "astroport-tokenfactory-tracker" | "astroport-whitelist";

export type JunoV1RequiredFrontendAddressKey = "astroport-factory" | "astroport-router" | "astroport-native-coin-registry" | "astroport-incentives";

export type JunoV1OptionalFrontendAddressKey = "astroport-oracle";

export type JunoV1FrontendAddressKey =
  | JunoV1RequiredFrontendAddressKey
  | JunoV1OptionalFrontendAddressKey;

export type NativeAssetInfo = { native_token: { denom: string } };
export type XykPairType = { xyk: Record<string, never> };

export interface JunoV1DeploymentNetwork {
  chain_id: "uni-7" | "juno-1" | string;
  bech32_prefix: "juno";
  fee_denom: string;
  native_asset_denom: "ujunox" | string;
}

export interface JunoV1FrontendConfig {
  required_addresses: JunoV1RequiredFrontendAddressKey[];
  optional_addresses: JunoV1OptionalFrontendAddressKey[];
  pair_discovery: string;
}

export interface JunoV1PairCreateMsgTemplate {
  pair_type: XykPairType;
  asset_infos: [NativeAssetInfo, NativeAssetInfo];
  init_params: null;
}

export interface JunoV1FrontendDeploymentConfig {
  network: JunoV1DeploymentNetwork;
  code_ids: Record<JunoV1CodeIdKey, number>;
  addresses: Record<JunoV1AddressKey, string>;
  pair_create_msg_template: JunoV1PairCreateMsgTemplate;
  frontend: JunoV1FrontendConfig;
}
