#!/usr/bin/env python3
"""Generate the TypeScript handoff type for Astroport-Juno v1 frontend config.

The committed deployment template is the source of truth for frontend-facing keys.
This generator emits a narrow declaration file that frontend code can import or
copy without learning every deployment-only field. It intentionally models only
v1 XYK launch scope: factory/router/registry/incentives plus optional oracle;
no prelaunch hardcoded pools, no DEX token, no stable/PCL surfaces.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any, NoReturn

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_TEMPLATE = ROOT / "deployment" / "juno-v1-testnet.template.json"
DEFAULT_OUTPUT = ROOT / "deployment" / "juno-v1-frontend-config.d.ts"


def fail(msg: str) -> NoReturn:
    print(f"FAIL: {msg}")
    sys.exit(1)


def load_template(path: pathlib.Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text())
    except FileNotFoundError:
        fail(f"missing deployment template: {path}")
    except json.JSONDecodeError as exc:
        fail(f"invalid deployment template JSON: {exc}")
    if not isinstance(data, dict):
        fail("deployment template must be a JSON object")
    return data


def require_string_list(cfg: dict[str, Any], path: str) -> list[str]:
    cur: Any = cfg
    for part in path.split("."):
        if not isinstance(cur, dict) or part not in cur:
            fail(f"missing {path}")
        cur = cur[part]
    if not isinstance(cur, list) or not all(isinstance(item, str) for item in cur):
        fail(f"{path} must be a string list")
    return cur


def require_dict(cfg: dict[str, Any], key: str) -> dict[str, Any]:
    value = cfg.get(key)
    if not isinstance(value, dict):
        fail(f"{key} must be an object")
    return value


def ts_union(values: list[str]) -> str:
    return " | ".join(json.dumps(value) for value in values)


def render(cfg: dict[str, Any]) -> str:
    network = require_dict(cfg, "network")
    addresses = require_dict(cfg, "addresses")
    code_ids = require_dict(cfg, "code_ids")
    required = require_string_list(cfg, "frontend.required_addresses")
    optional = require_string_list(cfg, "frontend.optional_addresses")

    all_frontend = required + optional
    missing = [key for key in all_frontend if key not in addresses]
    if missing:
        fail(f"frontend keys missing from addresses: {missing}")

    if "pools" in require_dict(cfg, "frontend") or "pairs" in require_dict(cfg, "frontend"):
        fail("frontend template must not hardcode pools/pairs")

    pair_template = require_dict(cfg, "pair_create_msg_template")
    pair_type = pair_template.get("pair_type")
    if not isinstance(pair_type, dict) or set(pair_type) != {"xyk"}:
        fail("pair_create_msg_template must stay XYK-only")

    code_keys = sorted(str(key) for key in code_ids)
    address_keys = sorted(str(key) for key in addresses)

    native = network.get("native_asset_denom")
    if not isinstance(native, str) or not native:
        fail("network.native_asset_denom must be a non-empty string")

    return f'''// AUTO-GENERATED by scripts/generate_juno_v1_frontend_types.py; do not edit by hand.
// Source: deployment/juno-v1-testnet.template.json

export type JunoV1CodeIdKey = {ts_union(code_keys)};

export type JunoV1AddressKey = {ts_union(address_keys)};

export type JunoV1RequiredFrontendAddressKey = {ts_union(required)};

export type JunoV1OptionalFrontendAddressKey = {ts_union(optional)};

export type JunoV1FrontendAddressKey =
  | JunoV1RequiredFrontendAddressKey
  | JunoV1OptionalFrontendAddressKey;

export type NativeAssetInfo = {{ native_token: {{ denom: string }} }};
export type XykPairType = {{ xyk: Record<string, never> }};

export interface JunoV1DeploymentNetwork {{
  chain_id: "uni-7" | "juno-1" | string;
  bech32_prefix: "juno";
  fee_denom: string;
  native_asset_denom: "{native}" | string;
}}

export interface JunoV1FrontendConfig {{
  required_addresses: JunoV1RequiredFrontendAddressKey[];
  optional_addresses: JunoV1OptionalFrontendAddressKey[];
  pair_discovery: string;
}}

export interface JunoV1PairCreateMsgTemplate {{
  pair_type: XykPairType;
  asset_infos: [NativeAssetInfo, NativeAssetInfo];
  init_params: null;
}}

export interface JunoV1FrontendDeploymentConfig {{
  network: JunoV1DeploymentNetwork;
  code_ids: Record<JunoV1CodeIdKey, number>;
  addresses: Record<JunoV1AddressKey, string>;
  pair_create_msg_template: JunoV1PairCreateMsgTemplate;
  frontend: JunoV1FrontendConfig;
}}
'''


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--template", type=pathlib.Path, default=DEFAULT_TEMPLATE)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if output is stale instead of writing it")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rendered = render(load_template(args.template))
    if args.check:
        try:
            current = args.output.read_text()
        except FileNotFoundError:
            fail(f"missing generated frontend type file: {args.output.relative_to(ROOT)}")
        if current != rendered:
            fail(f"stale generated frontend type file: {args.output.relative_to(ROOT)}")
        print("OK: Juno v1 frontend TypeScript handoff matches deployment template")
        print(f"output={args.output.relative_to(ROOT)} bytes={len(rendered)}")
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"OK: wrote {args.output.relative_to(ROOT)}")
    print(f"bytes={len(rendered)}")


if __name__ == "__main__":
    main()
